#!/usr/bin/env python
"""
Generate the Gauss-Legendre integration points and save them as a C file.
"""

import numpy as np

from sasmodels.special import roots_legendre


def gengauss(n, path):
    """
    Save the Gauss-Legendre integration points for length *n* into file *path*.
    """
    z, w = roots_legendre(n)

    # Make sure array size is a multiple of 4 otherwise some OpenCL devices
    # will misbehave
    if n%4 != 0:
        array_size = n + (4 - n%4)
        padding = [0.] * (4 - n%4)
        z, w = np.hstack((z, padding)), np.hstack((w, padding))
    else:
        array_size = n

    with open(path, "w") as fid:
        fid.write(f"""\
// Generated by sasmodels.gengauss.gengauss({n})

#ifdef GAUSS_N
# undef GAUSS_N
# undef GAUSS_Z
# undef GAUSS_W
#endif
#define GAUSS_N {n}
#define GAUSS_Z Gauss{n}Z
#define GAUSS_W Gauss{n}Wt
""")

        if array_size != n:
            fid.write("// Note: using array size %d so that it is a multiple of 4\n\n"%array_size)

        fid.write("constant double Gauss%dWt[%d]={\n"%(n, array_size))
        fid.write(",\n".join("\t% .15e"%v for v in w))
        fid.write("\n};\n")

        fid.write("constant double Gauss%dZ[%d]={\n"%(n, array_size))
        fid.write(",\n".join("\t% .15e"%v for v in z))
        fid.write("\n};")
